title: Magento PWA Documentation
description: Everything you need to build a Magento PWA.

source: src

theme: devdocs
logo: PWA Docs


github_link: true
feedback_link: true
github_repo: "https://github.com/magento-research/pwa-studio/"
github_files: "https://github.com/magento-research/pwa-studio/tree/master/pwa-devdocs/src/"


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "technologies"
    values:
      toc-group: "technologies"
  -
    scope:
      path: "pwa-buildpack"
    values:
      toc-group: "pwa-buildpack"
  -
    scope:
      path: "peregrine"
    values:
      toc-group: "peregrine"
  -
    scope:
      path: "venia-pwa-concept"
    values:
      toc-group: "venia-pwa-concept"


algolia:
  application_id: 'E642SEDTHL'
  index_name: 'pwa-devdocs'
  api_key: 'd2d0f33ab73e291ef8d88d8b565e754c'
  lazy_update: true
  excluded_files:
    - vagrant
    - common
    - js
    - i
    - schemas
    - static

google:
  analytics: 'UA-66243208-1'
