version: 2
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - master:
          filters:
            branches:
              only: master

# This key means nothing to CircleCI; it's just a place to keep anchored
# configuration nodes for reuse.
common_settings:
  docker: &docker_setup
    - image: 'circleci/node:10.14.1'
  # Cache a bunch of stuff
  # - npm's local tarball cache
  save_cache: &savecache
    paths:
      - ~/.ssh
      - ~/.npm
      - /root/.npm
    key: 'v3-npm-cache-{{ checksum "package-lock.json" }}'

  install_latest_npm: &install_latest_npm
    name: Ensure NPM is up to date
    command: sudo npm install -g npm@latest

  install_packages: &install_packages
    name: Install NPM packages from lockfile
    command: npm ci --ignore-scripts && npx lerna bootstrap --hoist --no-ci && npm rebuild

  full_build: &full_build
    name: Full Build
    command: 'cp packages/venia-concept/.env.dist packages/venia-concept/.env && npm run build && npm run clean:dist'

  test_result_path: &test_result_path
    path: "test-results"

jobs:
  master:
    docker: *docker_setup
    steps:
      - checkout
      - run: *install_latest_npm
      - run: *install_packages
      - run:
          name: Test Suites
          command: 'npm run test:ci'
      - run:
          name: Coveralls Coverage Analysis
          command: npm run coveralls
      - run: *full_build
      - store_test_results: *test_result_path
      - store_artifacts: *test_result_path
  build:
    docker: *docker_setup
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v3-npm-cache-{{ checksum "package-lock.json" }}'
      - run: *install_latest_npm
      - run: *install_packages
      - save_cache: *savecache
      - run:
          name: Test Suites and Coverage
          # Test failures should not stop Danger, so hide the exit code.
          command: 'npm run test:ci && npm run coveralls || true'
      - run: *full_build
      - run:
          name: DangerCI
          command: npm run danger

      - store_test_results: *test_result_path
      - store_artifacts: *test_result_path


